services:
  keycloak-service:
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_HOSTNAME: 91.99.230.244
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres_keycloak
      KC_DB_PASSWORD: password_keycloak
      KC_REALM_NAME: ofk-micro
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_keycloak
      KC_HOSTNAME_STRICT_HTTPS: false
  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  userprofile:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  post:
    env_file:
      - ./post-service/.env.prod
    environment:
      - NODE_ENV=prod
