spring:
  application:
    name: gateway-service

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://91.99.230.244:8180/realms/ofk-micro

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: user-profile-service
              uri: http://userprofile:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - name: RequestHeaderToRequestHeader
                  args:
                    headers:
                      X-User-Sub: "principal['sub']"

            - id: post-service
              uri: http://post-service:3000
              predicates:
                - Path=/api/posts
              filters:
                - StripPrefix=1
                - name: RequestHeaderToRequestHeader
                  args:
                    headers:
                      X-User-Sub: "principal['sub']"

          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://91.99.230.244:4200,http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders: "*"
                allowCredentials: true