name: Deploy to Hetzner

on:
  push:
    branches:
      - master  # Change if you use a different deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/hetzner_key
          chmod 600 ~/.ssh/hetzner_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project files to Hetzner
        run: |
          rsync -avz -e "ssh -i ~/.ssh/hetzner_key" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/ofk-app

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/hetzner_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/ofk-app
            docker compose down
            docker compose up -d --build
            docker system prune -f -a --volumes
          EOF
